name: player update scraper
on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: player scraper
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Install dependencies
        run: yarn install; yarn upg; yarn dev

      - name: push
        run: |
          git add .
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git commit -am "daily update"
          git push
